# Generated by Django 4.0 on 2021-12-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(default='No id', max_length=264),
        ),
    ]
